config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: :logout
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  scope :ordering, -> { order(:created_at) }

  validates :body, presence: true, length: {minimum: 2 ,maximum: 200}

  def edit_by?(current_user)
    current_user == user || current_user&.admin?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, -> { ordering }, dependent: :destroy

  scope :ordering, -> { order(created_at: :desc) }
  scope :full, -> { includes(:user).merge(User.with_attached_avatar) }
  validates :title, presence: true, length: {in: 2..255}
  validates :body, presence: true

  def edit_by?(current_user)
    current_user == user || current_user&.admin?
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
    has_one_attached :avatar

  has_many :posts, -> { ordering }, dependent: :destroy
  has_many :comments, -> { ordering }, dependent: :destroy

  scope :ordering, -> { order(:name) }


  validates :name, presence: true, length: {in: 2...100}
  validates :login, presence: true, length: {in: 2..100}, uniqueness: {case_sensetive: false}
    validate :check_avatar

  def edit_by?(current_user)
    current_user && (current_user == self || current_user.admin?)
  end


  private


  def check_avatar
    if avatar.attached? && !avatar.content_type.start_with?('image/')
      errors.add(:avatar, 'должно быть изображением')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_current_user

  private

  def load_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def check_authentication
    render_error unless @current_user
  end

  def render_error(error = t('helpers.forbidden'))
    @error = error
    render 'error', status: 403
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_authentication
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :check_edit, only: [:edit, :update, :destroy]

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = @current_user

    if @comment.save
      redirect_to @comment.post, notice: t('.success')
    else
      @post = @comment.post
      render 'posts/show'
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    if @comment.update(comment_params)
      redirect_to @comment.post, notice: t('.success')
    else
      render :edit 
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:post_id, :body)
  end

  def check_edit
    render_error unless @comment.edit_by?(@current_user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_authentication, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_edit, only: [:edit, :update, :destroy]
  after_action :increment_views_count, only: :show

  # GET /posts
  def index
    @posts = Post.includes(:user).ordering.page(params[:page])
  end

  # GET /posts/1
  def show
    @post = Post.includes(:user, comments: :user).find(params[:id])
    @comment = Comment.new(post: @post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.user = @current_user
    if @post.save
      redirect_to @post, notice: t('.success')
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: t('.success')
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_path, notice: t('.success')
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:body, :title)
  end

  def check_edit
    render_error unless @post.edit_by?(@current_user)
  end

  def increment_views_count
    @post.increment!(:views_count)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(login: params[:login])
    unless @user
      flash[:danger] = t('.user_not_found')
      redirect_to login_path
      return
    end
    if @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: t('.success')
    else
      flash[:danger] = t('.invalid_password')
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_edit, only: [:edit, :update, :destroy]

  # GET /users
  def index
    @users = User.ordering.page(params[:page])
  end

  # GET /users/1
  def show
    @posts = @user.posts.includes(:user).page(params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: t('.success')
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: t('.success')
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_path, notice: t('.success')
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:login, :name, :password, :password_confirmation, 
:avatar
)
  end

  def check_edit
    render_error unless @user.edit_by?(@current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render 'error_messages_for', object: object
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_error_messages_for.html.erb
<% if object.errors.any? %>
<div class="alert alert-danger">
  <h4 class="alert-heading">
    <%= t('activerecord.errors.title') %>
  </h4>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>

</div>
<% end %>

app/views/application/_flash.html.erb
<% flash.each do |key, msg| %>
  <div class="alert alert-<%=key%>">
    <%= msg %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <%=link_to t('app.name'), root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t('posts.index.btn'), posts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('users.index.btn'), users_path, class: 'nav-link' %>
      </li>      
    </ul>
    <% if @current_user %>
    <ul class="navbar-nav">
      <li class='nva-item dropdown'>
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= @current_user.login %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
          <%= link_to t('users.show.btn'), @current_user, class: 'dropdown-item' %>
          <%= link_to t('sessions.destroy.btn'), logout_path, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
    <%else%>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to t('users.new.btn'), new_user_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('sessions.new.btn'), login_path, class: 'nav-link' %>
      </li>
    </ul>
    <%end%>
  </div>
</nav>

app/views/application/error.html.erb
<div class="alert alert-danger">
  <h1 class='alert-heading'>
    <%= @error %>
  </h1>
</div>

app/views/comments/_comment.html.erb
<div class="card my-2">
  <div class="card-header">
    <%= comment.user.name %>
  </div>
  <div class="card-body">
    <p>
      <%= comment.body %>
    </p>
    <% if comment.edit_by?(@current_user) %>
    <%= link_to t('comments.edit.btn'), edit_comment_path(comment), class: 'card-link' %>
    <%= link_to t('comments.destroy.btn'), comment, class: 'text-danger card-link', data: {method: :delete, confirm: t('helpers.sure')} %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <%= error_messages_for comment %>
  <%= form.hidden_field :post_id %>
  <div class="form-group">
    <%= form.text_area :body, class: 'form-control', placeholder: Comment.human_attribute_name(:body) %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', comment: @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Блоги</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'my_application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'navbar' %>
  <main class='container'>
    <%= render 'flash' %>
    <%= yield %>
  </main>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <%= error_messages_for(post) %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card my-2">
  <div class="card-body">
    <h4 class="card-title">
      <%= post.title %>
    </h4>
    <h6 class="card-subtitle mb-2">
      <%= image_tag post.user.avatar.variant(resize_to_limit: [32, 32]), alt: post.user.login%>

      <%=link_to post.user.name, post.user, class: 'text-muted' %>
    </h6>

    <p class="card-text">
      <%= post.body %>
    </p>
    <% unless current_page?(post) %>
      <%= link_to t('posts.show.btn'), post, class: 'card-link' %>
    <% end %>
    <% if post.edit_by?(@current_user) %>
      <%= link_to t('posts.edit.btn'), edit_post_path(post), class: 'card-link' %>
      <%= link_to t('posts.destroy.btn'), post, class: 'card-link text-danger', data: {method: :delete, confirm: t('helpers.sure')} %>
    <% end %>
  </div>
  <div class="card-footer text-muted">
    <%=l post.created_at, format: :long %>
  </div>

</div>

app/views/posts/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>
<%= link_to t('posts.new.btn'), new_post_path, class: 'btn btn-primary' %>
<%= render @posts %>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render @post %>
<h4><%= Post.human_attribute_name(:comments) %></h4>
<% if @post.comments.blank? %>
<div class="alert alert-info">
<%= t('.comments_not_found') %>
</div>
<% else %>
<%= render @post.comments %>
<%end%>
<%= render 'comments/form', comment: @comment %>
<div class="text-muted">
<%= "#{Post.human_attribute_name(:views_count)}:" %>
<%= @post.views_count %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <%= error_messages_for(user) %>


  <div class="form-group">
    <%= form.label :login %>
    <%= form.text_field :login, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>




  <div class="actions">
    <%= form.submit t('.submit'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>
  <%= t '.title'  %>
</h1>
<div class="list-group">
  <% @users.each do |user| %>
  <%= link_to user.name, user, class: 'list-group-item list-group-item-action' %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1><%= t('.title') %></h1>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1><%= @user.login %></h1>
<h3 class="text-muted"><%= @user.name %></h3>
<% if @user.avatar.attached? %>
<%= image_tag @user.avatar.variant(resize_to_limit: [300, 300]), alt: post.user.login%>
<% end %>

<% if @user.edit_by?(@current_user) %>
<div class="mb-4">
<%= link_to t('users.edit.btn'), edit_user_path(@user), class: 'btn btn-primary' %>
<%= link_to t('users.destroy.btn'), @user, class: 'btn btn-danger', data: {method: :delete, confirm: t('helpers.sure')} %>
</div>
<% end %>
<%= render @posts %>
<%= paginate @posts %>